# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
pod 'SwiftyJSON'
target 'RayeRayeApp_DesignModel' do

end

target 'RayeRayeApp_DesignModelTests' do

end

